DROP TABLE C##ORCL.USER_GRADE CASCADE CONSTRAINTS;

CREATE TABLE C##ORCL.USER_GRADE
(
  GR_PK       VARCHAR2(45 BYTE) NOT NULL,
  USER_GR_CD  VARCHAR2(40 BYTE) NOT NULL,
  USER_PK     NUMBER(10) NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE C##ORCL.USER_GRADE IS '회원 등급';

COMMENT ON COLUMN C##ORCL.USER_GRADE.GR_PK IS 'PK';

COMMENT ON COLUMN C##ORCL.USER_GRADE.USER_GR_CD IS '등급 코드';

COMMENT ON COLUMN C##ORCL.USER_GRADE.USER_PK IS '회원 PK';


ALTER TABLE C##ORCL.USER_GRADE ADD (
  PRIMARY KEY
  (GR_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);




