
  CREATE TABLE "C##MYUSER"."MOVIE_RELATION" 
   (	"RELATION_PK" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"MV_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"MVT_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"MVT_SCREEN" NUMBER(10,0) NOT NULL ENABLE, 
	"FROM_DT" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"TO_DT" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"RUNNING_TIME" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"TYPE_CD" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"REG_DT" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"EDIT_DT" VARCHAR2(45 BYTE), 
	 PRIMARY KEY ("RELATION_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."RELATION_PK" IS '매핑 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."MV_PK" IS '영화 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."MVT_PK" IS '상영관 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."MVT_SCREEN" IS '영화 상영관';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."FROM_DT" IS '영화 시작 시간';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."TO_DT" IS '영화 종료시간';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."RUNNING_TIME" IS '영화 상영시간';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."TYPE_CD" IS '영화관 스크린 종류(3D/4D/IMAX)';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."REG_DT" IS '등록일자';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_RELATION"."EDIT_DT" IS '수정일자';
   COMMENT ON TABLE "C##MYUSER"."MOVIE_RELATION"  IS '영화상영관매핑';

