DROP TABLE C##ORCL.BOARD CASCADE CONSTRAINTS;

CREATE TABLE C##ORCL.BOARD
(
  BOARD_PK       NUMBER(10)                     NOT NULL,
  USER_PK        NUMBER(10)                     NOT NULL,
  TYPE_CD        NUMBER(10)                     NOT NULL,
  BOARD_TITLE    VARCHAR2(500 BYTE)             NOT NULL,
  BOARD_COMMENT  VARCHAR2(1000 BYTE)            NOT NULL,
  USER_ID        VARCHAR2(45 BYTE),
  REG_ID         VARCHAR2(45 BYTE),
  REG_DT         DATE,
  EDIT_ID        VARCHAR2(45 BYTE),
  EDIT_DT        DATE,
  SHOW_COUNT     VARCHAR2(45 BYTE),
  OPEN_YN        VARCHAR2(45 BYTE),
  FILE_ID        VARCHAR2(45 BYTE)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE C##ORCL.BOARD IS '게시판';

COMMENT ON COLUMN C##ORCL.BOARD.BOARD_PK IS '북마크 키';

COMMENT ON COLUMN C##ORCL.BOARD.USER_PK IS '사용자 키';

COMMENT ON COLUMN C##ORCL.BOARD.TYPE_CD IS '구분 코드';

COMMENT ON COLUMN C##ORCL.BOARD.BOARD_TITLE IS '게시글 제목';

COMMENT ON COLUMN C##ORCL.BOARD.BOARD_COMMENT IS '게시판 내용';

COMMENT ON COLUMN C##ORCL.BOARD.USER_ID IS '사용자 ID';

COMMENT ON COLUMN C##ORCL.BOARD.REG_ID IS '동록자 ID';

COMMENT ON COLUMN C##ORCL.BOARD.REG_DT IS '등록일자';

COMMENT ON COLUMN C##ORCL.BOARD.EDIT_ID IS '수정자 ID';

COMMENT ON COLUMN C##ORCL.BOARD.EDIT_DT IS '수정일자';

COMMENT ON COLUMN C##ORCL.BOARD.SHOW_COUNT IS '읽은 수';

COMMENT ON COLUMN C##ORCL.BOARD.OPEN_YN IS '공개 여부';

COMMENT ON COLUMN C##ORCL.BOARD.FILE_ID IS '파일 ID';


ALTER TABLE C##ORCL.BOARD ADD (
  PRIMARY KEY
  (BOARD_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


--  There is no statement for index C##ORCL.SYS_C007507.
--  The object is created when the parent object is created.
