
  CREATE TABLE "C##MYUSER"."MOVIE_COMMENT" 
   (	"COMMENT_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"MV_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"MOVIE_COMMENT" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"RECOM_YN" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"SCORE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"REG_DT" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"EDIT_DT" VARCHAR2(45 BYTE), 
	 PRIMARY KEY ("COMMENT_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."COMMENT_PK" IS '댓글 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."MV_PK" IS '영화 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."USER_PK" IS '유저 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."MOVIE_COMMENT" IS '댓글 내용';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."RECOM_YN" IS '대댓글 여부';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."SCORE" IS '좋아요 수';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."REG_DT" IS '등록일자';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_COMMENT"."EDIT_DT" IS '수정일자';
   COMMENT ON TABLE "C##MYUSER"."MOVIE_COMMENT"  IS '사용자';

