
  CREATE TABLE "C##MYUSER"."MOVIE_PICTRA" 
   (	"PT_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"MV_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"TRAILER_URL" VARCHAR2(200 BYTE), 
	"PICTURE1_URL" VARCHAR2(200 BYTE), 
	"PICTURE2_URL" VARCHAR2(200 BYTE), 
	"PICTURE3_URL" VARCHAR2(200 BYTE), 
	"PICTURE4_URL" VARCHAR2(200 BYTE), 
	"PICTURE5_URL" VARCHAR2(200 BYTE), 
	"REG_DT" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"EDIT_DT" VARCHAR2(45 BYTE), 
	 PRIMARY KEY ("PT_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."PT_PK" IS '사진영상 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."MV_PK" IS '영화 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."TRAILER_URL" IS '영상 URL';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."PICTURE1_URL" IS '사진1 URL';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."PICTURE2_URL" IS '사진2 URL';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."PICTURE3_URL" IS '사진3 URL';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."PICTURE4_URL" IS '사진4 URL';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."PICTURE5_URL" IS '사진5 URL';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."REG_DT" IS '변경일자';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE_PICTRA"."EDIT_DT" IS '수정일자';
   COMMENT ON TABLE "C##MYUSER"."MOVIE_PICTRA"  IS '사진_영상';

