DROP TABLE C##ORCL.PAYMENT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE C##ORCL.PAYMENT_HISTORY
(
  HISTORY_PK   VARCHAR(45 BYTE) NOT NULL,
  USER_PK      NUMBER(10) NOT NULL,
  USER_ACCOUNT VARCHAR2(45 BYTE),
  PAY          VARCHAR2(45 BYTE) NOT NULL,
  PAY_TYPE_CD  VARCHAR2(40 BYTE) NOT NULL,
  STATUS_CD    VARCHAR2(40 BYTE) NOT NULL,
  MOVIE_ID     VARCHAR2(45 BYTE),
  MOVIE_NM     VARCHAR2(45 BYTE),
  MOVIE_TIME   VARCHAR2(45 BYTE),
  PAY_TIME     VARCHAR2(45 BYTE)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE C##ORCL.PAYMENT_HISTORY IS '결제';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.HISTORY_PK IS '인덱스 PK';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.USER_PK IS '유저 PK';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.USER_ACCOUNT IS '회원 계좌번호';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.PAY IS '결제금액';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.PAY_TYPE_CD IS '결제방식';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.STATUS_CD IS '결제상태';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.MOVIE_ID IS '영화 아이디';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.MOVIE_NM IS '영화명';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.MOVIE_TIME IS '영화시간';

COMMENT ON COLUMN C##ORCL.PAYMENT_HISTORY.PAY_TIME IS '결제시간';


ALTER TABLE C##ORCL.PAYMENT_HISTORY ADD (
  PRIMARY KEY
  (HISTORY_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);