DROP TABLE C##ORCL.BOARD_COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE C##ORCL.BOARD_COMMENTS
(
  COMMENTS_PK  NUMBER(10)                       NOT NULL,
  BOARD_PK     NUMBER(10)                       NOT NULL,
  USER_PK      NUMBER(10)                       NOT NULL,
  RECOMMENT    VARCHAR2(200 BYTE),
  USER_ID      NUMBER(10)                       NOT NULL,
  LIKE_COUNT   VARCHAR2(200 BYTE),
  BR_CONTENTS  VARCHAR2(200 BYTE)               NOT NULL,
  REG_ID       VARCHAR2(45 BYTE)                NOT NULL,
  REG_DT       DATE                             NOT NULL,
  EDIT_ID      VARCHAR2(45 BYTE),
  EDIT_DT      DATE
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE C##ORCL.BOARD_COMMENTS IS '댓글';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.COMMENTS_PK IS '댓글 키';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.BOARD_PK IS '게시판 키';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.USER_PK IS '사용자 키';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.RECOMMENT IS '대댓글';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.USER_ID IS '사용자 ID';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.LIKE_COUNT IS '종아요 수';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.BR_CONTENTS IS '댓글';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.REG_ID IS '동록자 ID';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.REG_DT IS '등록일자';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.EDIT_ID IS '수정자 ID';

COMMENT ON COLUMN C##ORCL.BOARD_COMMENTS.EDIT_DT IS '수정일자';
