
  CREATE TABLE "C##MYUSER"."MOVIE" 
   (	"MV_PK" NUMBER(10,0) NOT NULL ENABLE, 
	"MV_NM" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"MV_TIME" VARCHAR2(45 BYTE), 
	"STATUS_CD" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"GRADE" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"MV_TYPE" VARCHAR2(45 BYTE), 
	"MV_ACTOR" VARCHAR2(45 BYTE), 
	"MV_DIRECTOR" VARCHAR2(45 BYTE), 
	"CREAT_YEAR" VARCHAR2(45 BYTE), 
	"MV_COUNTRY" VARCHAR2(45 BYTE), 
	"BOOKMARK_BM_PK" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("MV_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_PK" IS '영화 키';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_NM" IS '영화 이름';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_TIME" IS '영화 상영시간';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."STATUS_CD" IS '영화 시청 상태';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."GRADE" IS '시청 가능 등급';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_TYPE" IS '영화 장르';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_ACTOR" IS '출연 배우';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_DIRECTOR" IS '제작 감독';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."CREAT_YEAR" IS '영화 제작년도';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."MV_COUNTRY" IS '영화 제작 국가';
   COMMENT ON COLUMN "C##MYUSER"."MOVIE"."BOOKMARK_BM_PK" IS '북마크 키';
   COMMENT ON TABLE "C##MYUSER"."MOVIE"  IS '영화';

