DROP TABLE C##SCOTT.CGV_USER CASCADE CONSTRAINTS;

CREATE TABLE C##SCOTT.CGV_USER
(
  USER_PK         NUMBER(10)                    NOT NULL,
  USER_ID         VARCHAR2(50 BYTE)             NOT NULL,
  USER_NM         VARCHAR2(20 BYTE)             NOT NULL,
  USER_PASS       VARCHAR2(100 BYTE)            NOT NULL,
  ADMIN_YN        VARCHAR2(1 BYTE)              NOT NULL,
  USER_PHONE      NUMBER(11)                    NOT NULL,
  USER_ADR        VARCHAR2(100 BYTE),
  REG_ID          VARCHAR2(45 BYTE)             NOT NULL,
  REG_DT          DATE                          NOT NULL,
  EDIT_ID         VARCHAR2(45 BYTE),
  EDIT_DT         DATE,
  USER_EMAIL      VARCHAR2(45 BYTE)             NOT NULL,
  USER_SEX        VARCHAR2(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  USER_JUMIN      VARCHAR2(45 BYTE)             NOT NULL,
  USER_YN         VARCHAR2(1 BYTE)              NOT NULL,
  NON_USER_NM     VARCHAR2(20 BYTE),
  NON_USER_PHONE  VARCHAR2(11 BYTE),
  NON_USER_PASS   VARCHAR2(100 BYTE),
  NON_USER_ID     VARCHAR2(50 BYTE)             NOT NULL,
  USER_POINT      NUMBER(10)                    DEFAULT 0
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE C##SCOTT.CGV_USER IS '사용자';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_PK IS 'PK 구분값';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_ID IS '사용자 실명';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_NM IS '사용자 실명';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_PASS IS '사용자 비밀번호';

COMMENT ON COLUMN C##SCOTT.CGV_USER.ADMIN_YN IS '관리자 여부';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_PHONE IS '사용자 전화번호';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_ADR IS '사용자 주소';

COMMENT ON COLUMN C##SCOTT.CGV_USER.REG_ID IS '등록자ID';

COMMENT ON COLUMN C##SCOTT.CGV_USER.REG_DT IS '등록일자';

COMMENT ON COLUMN C##SCOTT.CGV_USER.EDIT_ID IS '수정자ID';

COMMENT ON COLUMN C##SCOTT.CGV_USER.EDIT_DT IS '수정일자';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_EMAIL IS '회원 이메일';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_SEX IS '회원 성별';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_JUMIN IS '회원 주민번호';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_YN IS '회원 비회원 여부';

COMMENT ON COLUMN C##SCOTT.CGV_USER.NON_USER_NM IS '비회원 이름';

COMMENT ON COLUMN C##SCOTT.CGV_USER.NON_USER_PHONE IS '비회원 핸드폰 번호';

COMMENT ON COLUMN C##SCOTT.CGV_USER.NON_USER_PASS IS '비회원 비밀번호';

COMMENT ON COLUMN C##SCOTT.CGV_USER.NON_USER_ID IS '비회원 아이디';

COMMENT ON COLUMN C##SCOTT.CGV_USER.USER_POINT IS '회원 포인트';
